name: Build and Deploy

on:
  push:
    branches: [ grav/deploy ]
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: check aws creds
        run: |
          aws s3api list-objects --endpoint-url "$S3_ENDPOINT_URL" --bucket "$S3_BUCKET" 
          exit 42

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Clojure tools (CLI + helpers)
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest

      - name: Install ImageMagick (for favicon)
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Build and deploy
        env:
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          chmod +x deploy.sh
          ./deploy.sh
