name: Build and Deploy

on:
  push:
    branches: [ grav/deploy ]
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Clojure CLI
        run: |
          curl -fsSL https://github.com/clojure/tools.deps.raw/master/bin/install | bash

      - name: Install ImageMagick (for favicon)
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Build and deploy
        env:
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          chmod +x deploy.sh
          ./deploy.sh
